version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default:
      baghirasf1:
      bozforum:

networks:
  baghirasf1:
    external:
      name: baghirasf1_default
  bozforum:
    external:
      name: bozforum_default
